// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20250922195628_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Config.RiskProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DailyLossCapR")
                        .HasColumnType("numeric");

                    b.Property<int>("MaxConcurrent")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("NoEntryAfter")
                        .HasColumnType("time without time zone");

                    b.Property<decimal>("PerTradeRiskPct")
                        .HasColumnType("numeric");

                    b.Property<int>("SlippageBps")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("risk_profiles", (string)null);
                });

            modelBuilder.Entity("Domain.Signals.Signal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Expiry")
                        .HasColumnType("date");

                    b.Property<string>("OptionSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasonJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StrategyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Strike")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("signals", (string)null);
                });

            modelBuilder.Entity("Domain.Strategies.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AiThreshold")
                        .HasColumnType("numeric");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RiskProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("strategies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
